-- CRIAR A DATABASE AUT_RES MANUALMENTE

-- QUERY 1

CREATE SCHEMA AUT_RESIDENCIA;

CREATE TABLE AUT_RESIDENCIA.PROJETO
(
ID BIGSERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(100),
DATA_CADASTRO TIMESTAMP DEFAULT NOW()
);

CREATE TABLE AUT_RESIDENCIA.AMBIENTE
(
ID BIGSERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(100),
DATA_CADASTRO TIMESTAMP DEFAULT NOW(),
ID_PROJETO BIGINT REFERENCES AUT_RESIDENCIA.PROJETO (ID)
);

CREATE TABLE AUT_RESIDENCIA.LUMINARIA
(
ID BIGSERIAL NOT NULL PRIMARY KEY,
NOME VARCHAR(100),
ESTADO VARCHAR(30),
DATA_CADASTRO TIMESTAMP DEFAULT NOW(),
ID_AMBIENTE BIGINT REFERENCES AUT_RESIDENCIA.AMBIENTE (ID)
);


-- QUERY 2 - POPULAR BANCO DE DADOS

INSERT INTO AUT_RESIDENCIA.PROJETO (NOME) VALUES ('Casa Cidade');

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Garagem', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Sala', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Cozinha', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Quarto 1', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Quarto 2', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Banheiro Quarto 1', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Banheiro Compartilhado', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Corredor Externo 1', 1);

INSERT INTO AUT_RESIDENCIA.AMBIENTE (NOME, ID_PROJETO) VALUES ('Quintal', 1);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'DESLIGADO', 1);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 2', 'DESLIGADO', 1);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 3', 'LIGADO', 1);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'DESLIGADO', 2);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 2', 'LIGADO', 2);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'DESLIGADO', 3);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 2', 'LIGADO', 3);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'DESLIGADO', 4);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'LIGADO', 5);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'DESLIGADO', 6);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'DESLIGADO', 7);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'LIGADO', 8);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 2', 'LIGADO', 8);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 1', 'LIGADO', 9);

INSERT INTO AUT_RESIDENCIA.LUMINARIA (NOME, ESTADO, ID_AMBIENTE) VALUES ('Lampada 2', 'LIGADO', 9);